/** Maps internal book slugs to YouVersion USFM book codes. */
export const BOOK_TO_USFM: Record<string, string> = {
  genesis: 'GEN',
  exodo: 'EXO',
  levitico: 'LEV',
  numeros: 'NUM',
  deuteronomio: 'DEU',
  josue: 'JOS',
  juizes: 'JDG',
  rute: 'RUT',
  '1-samuel': '1SA',
  '2-samuel': '2SA',
  '1-reis': '1KI',
  '2-reis': '2KI',
  '1-cronicas': '1CH',
  '2-cronicas': '2CH',
  esdras: 'EZR',
  neemias: 'NEH',
  ester: 'EST',
  jo: 'JOB',
  salmos: 'PSA',
  proverbios: 'PRO',
  eclesiastes: 'ECC',
  canticos: 'SNG',
  isaias: 'ISA',
  jeremias: 'JER',
  lamentacoes: 'LAM',
  ezequiel: 'EZK',
  daniel: 'DAN',
  oseias: 'HOS',
  joel: 'JOL',
  amos: 'AMO',
  obadias: 'OBA',
  jonas: 'JON',
  miqueias: 'MIC',
  naum: 'NAM',
  habacuque: 'HAB',
  sofonias: 'ZEP',
  ageu: 'HAG',
  zacarias: 'ZEC',
  malaquias: 'MAL',
  mateus: 'MAT',
  marcos: 'MRK',
  lucas: 'LUK',
  joao: 'JHN',
  atos: 'ACT',
  romanos: 'ROM',
  '1-corintios': '1CO',
  '2-corintios': '2CO',
  galatas: 'GAL',
  efesios: 'EPH',
  filipenses: 'PHP',
  colossenses: 'COL',
  '1-tessalonicenses': '1TH',
  '2-tessalonicenses': '2TH',
  '1-timoteo': '1TI',
  '2-timoteo': '2TI',
  tito: 'TIT',
  filemom: 'PHM',
  hebreus: 'HEB',
  tiago: 'JAS',
  '1-pedro': '1PE',
  '2-pedro': '2PE',
  '1-joao': '1JN',
  '2-joao': '2JN',
  '3-joao': '3JN',
  judas: 'JUD',
  apocalipse: 'REV',
};

export function toUsfmBookCode(bookId: string): string {
  return BOOK_TO_USFM[bookId] ?? bookId.toUpperCase().slice(0, 3);
}
